import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased"> {/* 폰트 클래스를 제거 */}
        {children}
      </body>
    </html>
  );
}
